# Generated by Django 4.0.4 on 2022-06-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
    ]
