version: '3.5'

services:
    web:
        build: ./instagram_django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/web_django
        ports:
            - '8000:8000'
        depends_on:
            - db
    db:
        image: mysql:5.7
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: example
        restart: always
        volumes:
            - ./db_django:/var/lib/mysql
